vaadin/vaadin-radio-button

demo/group.html
test/performance/index.html
vaadin-radio-button-group.html
vaadin-radio-button.html

Improved accessibility for screen readers, added disabled demo, minor change to styles of vaadin-radio-button
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button/3)

Improved accessibility for screen readers, added disabled demo

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button/8)

Remove the readme placeholder with actual description

---

demo/radio-button-basic-demos.html
demo/radio-button-group-demos.html
package-lock.json
package.json
vaadin-radio-button-group.html
vaadin-radio-button.html

Connects to #12
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button/13)

Fix demos and changed self-calling function to ES6 style.

---

README.md
analysis.json
demo/demos.json
demo/index.html
demo/radio-group-demos.html
test/index.html
test/vaadin-radio-button.html
test/vaadin-radio-group.html
test/visual/default.html
vaadin-radio-button.html
vaadin-radio-group.html

Connects to #12
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button/16)

Radio group fixes

---

analysis.json
vaadin-radio-button.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button/20)

Dirty fix for name documentation

---

analysis.json
test/vaadin-radio-group.html
vaadin-radio-button.html
vaadin-radio-group.html

Connects to #15 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button/22)

Restored value property

---

demo/radio-group-demos.html

Fixes #29
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button/30)

Add vaadin-radio-group value demo

---

test/vaadin-radio-group.html
vaadin-radio-group.html

Fixes #23
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button/24)

Do not steal focus from the current component when changing value programmatically

---

vaadin-radio-button.html

Fixes #26 
Aligned with the checkbox which already has this fix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button/31)

Remove gray highlight when tapping disabled state

---

src/vaadin-radio-button.html
test/vaadin-radio-button.html

Fixes #35
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button/38)

Fix iron-form interoperability

---

test/vaadin-radio-button.html

Fixes #40
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button/41)

Fix tests to work with iron-form 2.1.0

---

src/vaadin-radio-group.html
test/vaadin-radio-group.html

Fixes #39
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button/42)

Preserve focus-ring attribute when navigating with arrow keys

---

src/vaadin-radio-group.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button/44)

Fix issue where safari 9 focuses input inside vaadin-radio-button

---

bower.json
theme/material/vaadin-radio-button-styles.html
theme/material/vaadin-radio-button.html
theme/material/vaadin-radio-group-styles.html
theme/material/vaadin-radio-group.html

Connected to vaadin/vaadin-material-styles#49
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button/64)

Adding theme/material

---

analysis.json
src/vaadin-radio-button.html
src/vaadin-radio-group.html

Connected to vaadin/components-team-tasks#403
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button/76)

Remove Polymer mention in the API docs [skip ci]

---

src/vaadin-radio-group.html
test/vaadin-radio-group.html

Fixes #80
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button/81)

Fix FF focus

---

src/vaadin-radio-group.html
theme/lumo/vaadin-radio-group-styles.html
theme/material/vaadin-radio-group-styles.html

Fixes #82
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button/83)

Fix required invalid label

---

theme/material/vaadin-radio-group-styles.html

Fixes #87 
Same as vaadin/vaadin-checkbox#121
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button/90)

Fix Material ripple cropped in Chrome [skip ci]

---

src/vaadin-radio-group.html
test/vaadin-radio-group.html

Fixes #91
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button/97)

Allow unselecting radio-group value programmatically

---

src/vaadin-radio-button.html
src/vaadin-radio-group.html
test/vaadin-radio-button.html
test/vaadin-radio-group.html

feat: add 'change' event

---

src/vaadin-radio-button.html
src/vaadin-radio-group.html
test/vaadin-radio-group.html

Add focused attribute to radio-group

---

src/vaadin-radio-button.html
test/vaadin-radio-button.html

Fixes #89 
Fixes #109
Also fixes the regression for ios12 from https://github.com/vaadin/vaadin-radio-button/commit/bd6e578a0e722c6fdb95f160e3d574a234fc9460

Fix ios 10 and 12 issues

---

src/vaadin-radio-group.html
test/vaadin-radio-group.html

RTL roving tabindex

---

index.html
package.json
rollup.config.js
src/vaadin-radio-button.ts
src/vaadin-radio-group.ts
vaadin-radio-button.html
vaadin-radio-button.ts
vaadin-radio-group.html
vaadin-radio-group.ts

Fixes #135 
Depends on #141 
Depends on #142 
Use this PR to test live demos. Will rebase it whenever above PRs are changed or merged.

LitElement conversion part 4: API docs

---

src/vaadin-radio-group.html

docs: add JSDoc for attributes [skip ci] (#158)

---

src/vaadin-radio-group.html
test/vaadin-radio-group.html

fix: change checked condition on button removal (#160)

---

src/vaadin-radio-group.html
test/vaadin-radio-group.html

cherry pick of https://github.com/vaadin/web-components/pull/2232 for v14
add missing test
Fixes vaadin/flow-components#955

fix: do not focus the field on helper element click

---

src/vaadin-radio-group.html
test/test-suites.js
test/validation.html

Backports the following PRs:
- https://github.com/vaadin/web-components/pull/4084
Part of https://github.com/vaadin/web-components/issues/5763

feat: fire a validated event on validation (CP: 14)

---

src/vaadin-radio-button.html
test/vaadin-radio-button.html

Cherry-pick of #230 to `1.5` branch for Vaadin 14.10
- Cherry-pick

fix: prevent selecting on mouseup outside the radio-button (#230) (CP: 1.5)
