vaadin-radio-button-group.html
vaadin-radio-button.html

Connects to https://github.com/vaadin/vaadin-control-state-mixin/pull/12
Remove `disabled` property and `aria-disabled` attribute as it is added in control-state-mixin.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button/7)

Remove disabled property and aria-disabled attribute

---

test/vaadin-radio-button.html

Now that PolymerElements/iron-form#239 is merged and released in `iron-form` 2.1.1 we can revert workaround used in tests. Also added native form, which was missed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button/43)

Restore iron-form tests

---

.travis.yml
test/vaadin-radio-button.html
test/vaadin-radio-group.html
wct.conf.js

Connected to vaadin/components-team-tasks#332
The `mock-interactions` change is intended to  to eliminate the `polymer-legacy.js` import from converted tests, and is needed because of the fact that `mock-interactions.js` still use the `Polymer.Base.async` and the HTML file imports the correspondent dependency.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button/54)

 Use bare module specifiers in the P3 conversion

---

src/vaadin-radio-button.html

I use the demo CDN to show an example.
With this `vaadin-radio-button`:
The `input[type="radio"]` it's outside the `span[part="radio"]` right now:
The `input[type="radio"]` with the PR change:
I recomend to open all the images in browser tabs, and move accross them to see easily.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button/60)

Remove margin on input[type="radio"]

---

demo/demos.json
demo/radio-button-basic-demos.html
demo/radio-group-demos.html
demo/radio-group-validation-demos.html

Connects to "Guidelines for component examples"
- Rename "Basic Examples" to "Radio Button"
- Created "Validation" demo page
- Renamed "Lumo Theme Variations" to "Theme Variants"
- Unified radio-button and radio-group demo example titles
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button/72)

Reorganize demos

---

src/vaadin-radio-group.html

Same as vaadin/vaadin-checkbox#116
Note: here it does not cause any issues, but we should avoid duplicate event listeners.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button/78)

Prevent adding duplicate listeners on re-attaching

---

src/vaadin-radio-button.html
test/vaadin-radio-button.html

Connected to #77.
Issue occurs because the FF forwards the focus natively to its control element when `.focus` is called.
So we are getting into the loop in `control-state-mixin` of moving focus between `label` and `input`.
`_cycleTab` in overlay getting the incorrect focused `index` and cannot move the focus to the next element. 
I have tried to implement the focus test here, but it seems to be impossible, so I am checking the behaviour in `overlay`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button/79)

Set input element to be the focusElement

---

src/vaadin-radio-button.html
test/vaadin-radio-button.html

Fixes #84
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button/85)

Set radio button checked on host click

---

theme/lumo/vaadin-radio-button-styles.html

Fixes #93 
Still not sure about the reason, but that helps as well as `overflow: hidden`
Note: can be reviewed and confirmed using `vaadin-notification` sampler demo mentioned in the issue. With the suggested fix, no space appears below the group compared to GIF reproduction.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button/98)

Workaround IE11 jumpiness issue

---

src/vaadin-radio-button.html

Fixes #95 
This partially reverts the original fix from af64a82b43693dd655bebe85a99cd2bb2165bee8
Looks like using properties block still allows to also have custom getter and setter.
Let's see if all the tests pass and if so, then use this approach.

docs(api): update name property to fix JSDoc issue

---

src/vaadin-radio-button.html
test/vaadin-radio-button.html

Fixes #121 
Note: now when this is fixed, there is another problem: user can listen to `change` event for `radio-group` and get bubbling event from `radio-button` before the radio group value is updated.
I'm wondering if we should handle that by catching that event with `stopImmediatePropagation` and then re-dispatching a proper `change` event from the radio group itself 🤔

fix: ensure change event on mouseup is fired

---

bower.json

There is already a commit merged to `master` that depends on `DirMixin`.
We should bump version and make it explicit that it needs a new minor.

feat: bump element-mixin to 2.3.0

---

.travis.yml
src/vaadin-radio-button.html

Selecting/checking a radio button did not work reliably on iOS 12 and 13.
Fixes #140.

fix: functionality for iOS 12 and 13

---

.travis.yml
src/vaadin-radio-button.html

Clean cherry-pick of https://github.com/vaadin/vaadin-radio-button/pull/143 for 1.2 branch. Manually tested on iOS 12 and 13 and confirmed working.
Fixes #140.

[1.2] fix: functionality for iOS 12 and 13

---

bower.json
gen-tsd.json
magi-p3-post.js
package.json
src/vaadin-radio-button.html
src/vaadin-radio-group.html

Fixes #150 
Generated TS definitions files look like this:
```ts
import {PolymerElement} from '@polymer/polymer/polymer-element.js';
import {GestureEventListeners} from '@polymer/polymer/lib/mixins/gesture-event-listeners.js';
import {ThemableMixin} from '@vaadin/vaadin-themable-mixin/vaadin-themable-mixin.js';
import {ControlStateMixin} from '@vaadin/vaadin-control-state-mixin/vaadin-control-state-mixin.js';
import {ElementMixin} from '@vaadin/vaadin-element-mixin/vaadin-element-mixin.js';
import {html} from '@polymer/polymer/lib/utils/html-tag.js';
declare class RadioButtonElement extends
ElementMixin(
ControlStateMixin(
ThemableMixin(
GestureEventListeners(
PolymerElement)))) {
readonly focusElement: HTMLInputElement;
name: string|null|undefined;
checked: boolean;
value: string; …
```

feat: prepare for TS defs generation [skip ci]

---

src/vaadin-radio-group.html

Connected to vaadin/vaadin-core#257
Note, this is a PR for `1.4` branch. When cherry-picking it to `1.5`, we need to also include `helperText` property.

docs: add JSDoc for attributes [skip ci]

---

src/vaadin-radio-group.html
test/vaadin-radio-group.html

Prior this change, the conditional checks whether the button being removed is checked or not, in order of resetting the group value.
That works well, unless a new button is checked right after the checked button is removed. Since the resetting logic is done inside a FlattenedNodesObserver, it happens asynchronously and the selected button being removed is no longer the actual value of the group, therefore no reset is needed.
Fix https://github.com/vaadin/vaadin-radio-button-flow/issues/108

fix: change checked condition on button removal 

---

theme/material/vaadin-radio-group.html

Fixes https://github.com/vaadin/web-components/issues/661

fix: add missing import for Material theme

---

src/vaadin-radio-button.html
test/vaadin-radio-button.html

Fixes https://github.com/vaadin/web-components/issues/442
Added logic to ensure `mouseup` event fired outside the `vaadin-radio-button` element doesn't make it selected.
This is needed because of the way how Polymer `downup` gesture is implemented, especially [`trackDocument()`](https://github.com/Polymer/polymer/blob/1e8b246d01ea99adba305ea04c45d26da31f68f1/lib/utils/gestures.js#L761).
- Bugfix

fix: prevent selecting on mouseup outside the radio-button

---

src/vaadin-radio-button.html
test/vaadin-radio-button.html

Fixes https://github.com/vaadin/web-components/issues/6911
The original fix only worked for `mouseup` event and was causing an error on touch devices.
When investigating this further, I realised that we can't rely on `event.composedPath()` anyway.
Luckily there is a helper in Polymer to get the actual target using event coordinates.
Updated the `up` event listener to use it. Also, extended unit tests accordingly.
- Bugfix

fix: detect actual target of the touchend or mouseup event
